version: "3.9"
name: challenge-im
services:
  challenge-im:
    build: .
    ports:
      - "${PORT}:5000"
    environment:
      - CLIENT_URL
      - API_URL
      - API_PATH
      - PORT=5000
      - SESSION_SECRET
      - DATABASE_URL
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET
      - SMTP_HOST
      - SMTP_USER
      - SMTP_PASSWORD
      - SMTP_PORT
      - SMTP_SECURE
